//
// Created by marcos on 19/6/20.
//

#ifndef ARGENTUM_MOVEDIRECTION_H
#define ARGENTUM_MOVEDIRECTION_H

enum Direction {
    DIRECTION_UP, DIRECTION_DOWN, DIRECTION_LEFT, DIRECTION_RIGHT
};

#endif //ARGENTUM_MOVEDIRECTION_H
