//
// Created by marcos on 7/5/20.
//

#ifndef ARGENTUM_TEXTUREID_H
#define ARGENTUM_TEXTUREID_H

enum TextureID {
    Nothing, /*Lo uso para el equipo del Player*/
    PlayerGhost,
    BlueTunic,
    BlueTunicDrop,
    CommonClothing,
    CommonClothingDrop,
    Hood,
    HoodDrop,
    IronHelmet,
    IronHelmetDrop,
    IronShield,
    IronShieldDrop,
    KingArmor,
    KingArmorDrop,
    LeatherArmor,
    LeatherArmorDrop,
    MagicHat,
    MagicHatDrop,
    PlateArmor,
    PlateArmorDrop,
    TurtleShield,
    TurtleShieldDrop,
    DwarfHead,
    ElfHead,
    GnomeHead,
    HumanHead,
    AshRod,
    AshRodDrop,
    Axe,
    AxeDrop,
    CompositeBow,
    CompositeBowDrop,
    ElvenFlute,
    ElvenFluteDrop,
    LinkedStaff,
    LinkedStaffDrop,
    GnarledStaff,
    GnarledStaffDrop,
    LongSword,
    LongSwordDrop,
    SimpleBow,
    SimpleBowDrop,
    WarHammer,
    WarHammerDrop,
    HealthPotion,
    ManaPotion,
    Grass,
    PrettyGrass,
    DeadGrass,
    PrettyRoad,
    Sand,
    Water,
    DarkWater,
    Skeleton,
    Goblin,
    Zombie,
    Spider,
    Priest,
    Trader,
    Banker,
    Guard,
    Tree,
    LongTree,
    FatTree,
    PalmTree,
    DeadTree,
    Bush,
    DeadBush,
    House1,
    House2,
    House3,
    SunkenColumn,
    SunkenShip,
    BoneGuy,
    BrokenRipStone,
    DeadGuy,
    VeryDeadGuy,
    HangedGuy,
    RipStone,
    Explosion,
    MagicArrow,
    MagicMissile,
    Heal,
    Background,
    MainMenu
};

#endif //ARGENTUM_TEXTUREID_H
