//
// Created by agustin on 19/7/20.
//

#ifndef ARGENTUM_NONMODIFIABLECONSTANTS_H
#define ARGENTUM_NONMODIFIABLECONSTANTS_H

#define MAX_NUMBER_OF_ITEMS_PER_PLAYER 20
#define INVENTORY_SIZE 16


#endif //ARGENTUM_NONMODIFIABLECONSTANTS_H
