//
// Created by agustin on 19/7/20.
//

#ifndef ARGENTUM_NONMODIFIABLECONSTANTS_H
#define ARGENTUM_NONMODIFIABLECONSTANTS_H

const int INVENTORY_SIZE = 16;
const int BANK_SIZE = 20;
const int MAX_NICKNAME_SIZE = 13;
const unsigned int INITIAL_PLAYER_GOLD = 150;

#endif //ARGENTUM_NONMODIFIABLECONSTANTS_H
